# Generated by Django 4.0.5 on 2022-07-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0011_student_cursuri'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='activ',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
