# Generated by Django 4.0.5 on 2022-07-19 17:15

from django.db import migrations


def forwards(apps, models):
    print("inainte")
    Student = apps.get_model("curs", "Student")
    Student.objects.update(activ="Da")


def backwards(apps, models):
    print("inapoi")
    Student = apps.get_model("curs", "Student")
    Student.objects.update(activ=None)

class Migration(migrations.Migration):

    dependencies = [
        ('curs', '0012_student_activ'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.RunPython(lambda *args: print("inainte1"), lambda *args: print("inapoi1"))
    ]
