services:
  db:
    image: postgres:14
    env_file: .env
  cache:
    image: memcached
    deploy:
      replicas: 1
  web:
    build: .
    volumes:
      - .:/siit
    expose:
      - 8000
    env_file: .env
    # deploy:
    #   replicas: 2
    command: local-server
    # For remote debugging 
    # use docker attach <container_name>
    tty: true
    stdin_open: true
    links:
      - db
      - cache
    depends_on:
      - db
      - cache
  loadbalancer:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - 8001:8001