services:
  db:
    image: postgres:14
    env_file: .env
  cache:
    image: memcached
    deploy:
      replicas: 4
  web:
    build: .
    volumes:
      - .:/siit
    ports:
      - 8000:8000
    env_file: .env
    links:
      - db
      - cache
    depends_on:
      - db
      - cache