services:
  db:
    image: postgres:14
    env_file: .env
  cache:
    image: memcached
    deploy:
      replicas: 2
  web:
    build: .
    volumes:
      - .:/siit
    expose:
      - 8000
    env_file: .env
    deploy:
      replicas: 6
    links:
      - db
      - cache
    depends_on:
      - db
      - cache
  loadbalancer:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - 8001:8001