# Generated by Django 4.0.5 on 2022-07-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curs2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelexemplu',
            options={'verbose_name_plural': 'Modele Exemplu'},
        ),
    ]
